# VPC Workflow
# 
# This workflow is responsible for creating VPCs. 

# Build Definition
steps:

  - id: Create VPC
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: bash
    args:
    - '-c'
    - |
      # Create VPC
      # scripts/create_vpc.sh --name "${_NAME}" --project "${PROJECT_ID}"

options:
  logging: CLOUD_LOGGING_ONLY

# Build Parameters
substitutions:

  _NAME:  demo-vpc-1